### ISSUE TITLE
对识别后的内容做字段提取有什么好的思路

### ISSUE THREAD

**Issue by kongcong** [chineseocr/chineseocr#100]
如果对一个铭牌或者表格进行识别，识别后的结果其实是将图片中的文字尽可能多的识别出来，如果想对识别出来的指定字段进行提取，有什么的好的方法吗？使用正则会比较麻烦，因为图片识别出来的结果，有一些是字段名和字段值在一行的，有一些会换到下一行输出。

**Comment by kongcong** [comment]
> 如果对一个铭牌或者表格进行识别，识别后的结果其实是将图片中的文字尽可能多的识别出来，如果想对识别出来的指定字段进行提取，有什么的好的方法吗？使用正则会比较麻烦，因为图片识别出来的结果，有一些是字段名和字段值在一行的，有一些会换到下一行输出。

@wenlihaoyu

**Comment by wenlihaoyu** [comment]
对结果再进行一次“行合并”，合并依据:两个box之间的cy之差小于给定的值，就进行合并。

**Comment by kongcong** [comment]
> 对结果再进行一次“行合并”，合并依据:两个box之间的cy之差小于给定的值，就进行合并。

如果文字是在同一行的应该可以，但是如果本身就是不在同一行，这种方法可能不是很可行

比如这种情况。而且根据对文本框的排序，这三个框的顺序也不一定挨着。

**Comment by kongcong** [comment]
如果文字是在同一行的应该可以，但是如果本身就是不在同一行，这种方法可能不是很可行
|日期       |                              |
|              |       2018-11-14     |
|DATE      |                              | 
比如这种情况。而且根据对文本框的排序，这三个框的顺序也不一定挨着。
