### ISSUE TITLE
使用crnn.pytorch训练识别部分遇到的问题

### ISSUE THREAD

**Issue by kongcong** [chineseocr/chineseocr#108]
在完成制作自己的数据集之后，将本项目中的ocr-lstm.pth作为预加载模型，修改crnn.pytorch项目中的crnn_main.py进行训练，运行后遇到问题
loading pretrained model from /mnt/data1/ocr/crnn.pytorch/models/ocr-lstm.pth
Traceback (most recent call last):
  File "crnn_main.py", line 105, in <module>
    crnn.load_state_dict(state_dict_rename)
  File "/home/xj/anaconda2/envs/ocr-pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for CRNN:
	Unexpected key(s) in state_dict: "cnn.batchnorm2.num_batches_tracked", "cnn.batchnorm4.num_batches_tracked", "cnn.batchnorm6.num_batches_tracked". 
查了相关资料后升级了pytorch的版本为0.4.1，虽然不报这个错误了，可是却一直卡在打印网络的这里不会往下进行训练了，这是什么原因导致的？是我们环境的问题吗？还是训练代码需要修改？
@wenlihaoyu

**Comment by zxczhkzxc** [comment]
@kongcong  我也遇到了这个问题,请问你这边解决了么? 直接用lstm 模型会有问题这种情况?

**Comment by YuqingWuu** [comment]
同求答案

**Comment by JoahHuang** [comment]
同求答案
