### ISSUE TITLE
环境报错ModuleNotFoundError: No module named 'web'

### ISSUE THREAD

**Issue by karmanzeng** [chineseocr/chineseocr#12]
作者你好！按照提供的说明部署来的，报错ModuleNotFoundError: No module named 'web'，该如何解决呢？谢谢

**Comment by karmanzeng** [comment]
核实过web已经安装了

**Comment by wenlihaoyu** [comment]
检查是否将web.py 安装到根目录环境了，或者用~/anaconda2/envs/chineseocr/bin/pip install 安装

**Comment by wenlihaoyu** [comment]
检测你安装的ipython 是系统root的还说chineseocr？或者直接运行：~/anaconda2/envs/chineseocr/bin/ipython app.py

**Comment by karmanzeng** [comment]
good
