### ISSUE TITLE
pushd detector/utils && sh make-for-cpu.sh && popd

### ISSUE THREAD

**Issue by xiaoaogongji** [chineseocr/chineseocr#125]
作者您好:
setup-cpu.md文件中
这句是不是路径是错误的？正确的是不是在text文件夹下面?
cd 到text文件夹下，执行报错,如下
error: /home/administrator/python/mycr/chineseocr/text/detector/utils/bbox.pyx
mv: 无法获取'utils/*' 的文件状态(stat): 没有那个文件或目录

不知道是不是我那里执行的不对？

望作者和大神们指导，谢谢

**Comment by wenlihaoyu** [comment]
已修复，编译文件忘记修改了。

**Comment by xiaoaogongji** [comment]
谢谢 大神
