### ISSUE TITLE
请问本项目可以用在车牌号识别吗？

### ISSUE THREAD

**Issue by beizhengren** [chineseocr/chineseocr#164]
首先感谢作者开源这么好的代码。
想问下有没有哪位朋友用于车牌号识别

**Comment by austingg** [comment]
Yes， just replace the training data

**Comment by beizhengren** [comment]
@austingg Thank you, and can this project  be a real-time detection in license-plate recognition?

**Comment by wenlihaoyu** [comment]
用于车牌号实时识别，需要修改一些代码。建议用其他项目，在CPU上均能够做到实时识别

**Comment by beizhengren** [comment]
@wenlihaoyu 谢谢
