### ISSUE TITLE
关于darknet输出out和y_true的疑惑

### ISSUE THREAD

**Issue by LingQiu** [chineseocr/chineseocr#181]
您好，对网络的输出out和y_true有些疑惑：
在`keras_yolo3.py`中393行`out = [y1,y2,y3]`，y1、y2、y3的最后一维是`num_anchors*(num_classes+5)`，而`y_true`的最后一维是`num_classes+5`，这两个shape不匹配，这样对吗？
谢谢。

**Comment by wenlihaoyu** [comment]
在最终计算loss环节，yolo_head 函数对 out进行了reshape，num_classes + 5 ，详细参考https://github.com/chineseocr/chineseocr/blob/master/text/keras_yolo3.py#L116

**Comment by LingQiu** [comment]
好的，谢谢回复
