### ISSUE TITLE
训练报错：TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by AlanNewImage** [chineseocr/chineseocr#184]
使用text-train.ipynb导出的.py文件，运行后出现上述报错。

**Comment by AlanNewImage** [comment]
报错的位置在

        lossName = ['class_loss','xy_loss','wh_loss','confidence_loss']   
        lossList = [Lambda(get_loss,output_shape=(1,),name=lossName[i],arguments={'index':i})(loss) for i in range(4)]
        textModel = Model([imgInput, y_true], lossList)

附近

**Comment by wenlihaoyu** [comment]
打开notebook，导出为.py文件即可。

**Comment by AlanNewImage** [comment]
训练权重保存路径在哪儿？@wenlihaoyu

**Comment by AlanNewImage** [comment]
识别结果的tensor里面的值为啥不是0-1？crnns.py里面
model.eval()
       preds = model(image)
       _, preds = preds.max(2)
preds值是比较小的负数，并不是0-1？

**Comment by AlanNewImage** [comment]
https://github.com/meijieru/crnn.pytorch/issues/40

**Comment by yuanshengyu** [comment]
> 
> 
> 使用text-train.ipynb导出的.py文件，运行后出现上述报错。

兄弟，这个最后怎么解决的？

**Comment by AlanNewImage** [comment]
> > 使用text-train.ipynb导出的.py文件，运行后出现上述报错。
> 
> 兄弟，这个最后怎么解决的？

py3还是py2来着。忘了，好像是python版本问题吧。具体忘记了

**Comment by yuanshengyu** [comment]
> 
> 
> > > 使用text-train.ipynb导出的.py文件，运行后出现上述报错。
> > 
> > 
> > 兄弟，这个最后怎么解决的？
> 
> py3还是py2来着。忘了，好像是python版本问题吧。具体忘记了

感谢回复。我是自己改代码改错了，不小心把image_shape和input_shape赋了list值
