### ISSUE TITLE
keras版本ocr报错问题

### ISSUE THREAD

**Issue by xdwjc** [chineseocr/chineseocr#209]
博主您好，很激动看到您又更新了项目，我用了keras版本的ocr测试，报如下这个错误，请问这是什么原因呢：
![error1](https://user-images.githubusercontent.com/44966943/55696561-2e943a00-59f0-11e9-9a22-aabe23712da1.png)

**Comment by wenlihaoyu** [comment]
检查tensorflow版本是否正确，建议不要用根目录环境。

**Comment by xdwjc** [comment]
> tensorflow版本是否正确，

**Comment by xdwjc** [comment]
> 检查tensorflow版本是否正确，建议不要用根目录环境。
您好 谢谢您的指导 问题解决了 是keras版本的问题 我之前装的是keras2.2.4,换成2.1.6就可以了

**Comment by xdwjc** [comment]
> 检查tensorflow版本是否正确，建议不要用根目录环境。

您好 谢谢您的指导 问题解决了 是keras版本的问题 我之前装的是keras2.2.4,换成2.1.6就可以了
