### ISSUE TITLE
how to train with the rctw dataset?

### ISSUE THREAD

**Issue by passion3394** [chineseocr/chineseocr#225]
I have downloaded the icdar2017rctw dataset, could you give me some help to train the dataset based on your models published in Baidu net disk?

**Comment by wenlihaoyu** [comment]
可以将数据转换为ICDR2019对应的格式，然后运行text-train-icdr2019.ipynb即可

**Comment by passion3394** [comment]
@wenlihaoyu 好的，谢谢。

**Comment by zzcqinag** [comment]
你好!text-train-icdr2019.ipynb这个文件里的train_labels.json可以共享下吗?

**Comment by kylechang523** [comment]
请问text_train_icdar2019.ipynb在哪个folder下面呀？
