### ISSUE TITLE
服务起来了，但是识别出现问题

### ISSUE THREAD

**Issue by Mankvis** [chineseocr/chineseocr#249]
58.246.102.89:53303 - - [15/May/2019 20:36:43] "HTTP/1.1 POST /ocr" - 500 Internal Server Error
58.246.102.89:53400 - - [15/May/2019 20:37:05] "HTTP/1.1 GET /ocr" - 200 OK
Traceback (most recent call last):
  File "/root/.virtualenvs/chineseocrEnv/lib/python3.5/site-packages/web/application.py", line 257, in process
    return self.handle()
  File "/root/.virtualenvs/chineseocrEnv/lib/python3.5/site-packages/web/application.py", line 248, in handle
    return self._delegate(fn, self.fvars, args)
  File "/root/.virtualenvs/chineseocrEnv/lib/python3.5/site-packages/web/application.py", line 488, in _delegate
    return handle_class(cls)
  File "/root/.virtualenvs/chineseocrEnv/lib/python3.5/site-packages/web/application.py", line 466, in handle_class
    return tocall(*args)
  File "/home/chineseocr/app.py", line 39, in POST
    data = json.loads(data)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

58.246.102.89:54835 - - [15/May/2019 20:48:10] "HTTP/1.1 POST /ocr" - 500 Internal Server Error

**Comment by Mankvis** [comment]
> 58.246.102.89:53303 - - [15/May/2019 20:36:43] "HTTP/1.1 POST /ocr" - 500 Internal Server Error
> 58.246.102.89:53400 - - [15/May/2019 20:37:05] "HTTP/1.1 GET /ocr" - 200 OK
> Traceback (most recent call last):
> File "/root/.virtualenvs/chineseocrEnv/lib/python3.5/site-packages/web/application.py", line 257, in process
> return self.handle()
> File "/root/.virtualenvs/chineseocrEnv/lib/python3.5/site-packages/web/application.py", line 248, in handle
> return self._delegate(fn, self.fvars, args)
> File "/root/.virtualenvs/chineseocrEnv/lib/python3.5/site-packages/web/application.py", line 488, in _delegate
> return handle_class(cls)
> File "/root/.virtualenvs/chineseocrEnv/lib/python3.5/site-packages/web/application.py", line 466, in handle_class
> return tocall(*args)
> File "/home/chineseocr/app.py", line 39, in POST
> data = json.loads(data)
> File "/usr/lib/python3.5/json/**init**.py", line 312, in loads
> s.**class**.**name**))
> TypeError: the JSON object must be str, not 'bytes'
> 
> 58.246.102.89:54835 - - [15/May/2019 20:48:10] "HTTP/1.1 POST /ocr" - 500 Internal Server Error

**Comment by ericosmic** [comment]
问题解决了吗? 我也遇到同样的问题
