### ISSUE TITLE
批处理预测乱序

### ISSUE THREAD

**Issue by ltm920716** [chineseocr/chineseocr#278]
当使用多张张相同大小的图片进行批处理预测时，yolo检测部分的输出框和socores是乱序的，导致图片最终得到的框也是对应到不同的图片上，应该是模型的输出中对于多张的同时处理有问题，可以解决一下么，谢谢

**Comment by wenlihaoyu** [comment]
要修改box_layer

**Comment by ltm920716** [comment]
@wenlihaoyu 是的，已解决
