### ISSUE TITLE
部署成服务cpu环境运行越来越慢,每次请求要多0.7s左右,内存增加60M左右 

### ISSUE THREAD

**Issue by 13718413797** [chineseocr/chineseocr#283]
前几次请求还好,4s就能返回结果5 6 次以后每次请求越来越慢,内存也越耗越多,到几十次请求后要60多秒才能返回结果,gpu运行还是比较稳定的没出现越来越慢的情况,请大神给指点下哪里出了问题

**Comment by 13718413797** [comment]
![image](https://user-images.githubusercontent.com/20590467/60250218-c838fc80-98f8-11e9-97e2-83607aa92a35.png)
![image](https://user-images.githubusercontent.com/20590467/60250246-d129ce00-98f8-11e9-8eb3-59499e5bcd07.png)

**Comment by 13718413797** [comment]
第一次请求内存情况
![image](https://user-images.githubusercontent.com/20590467/60250398-27970c80-98f9-11e9-880f-4e8a5eb72c58.png)
最后一次内存情况:内存被吃了700M左右
![image](https://user-images.githubusercontent.com/20590467/60250427-37aeec00-98f9-11e9-9400-9a627d137f61.png)

**Comment by wenlihaoyu** [comment]
没有复现你所说的情况，请详细说明你怎么测试，系统、内存、及各种参数配置。

**Comment by 13718413797** [comment]
系统centos6.9,服务器配置4核8线程,16G内存,python服务用的是Flask,使用的是cpu,角度检测用的是cv2.dnn,文字检测用的是keras_detect,文字识别用的是crnn_torch,一定要多试些图片  有的时候从第二次请求就开始慢了  有的时候要请求10几次才开始慢,只要一开始慢就会请求一次慢一次一直累加的慢下去,我试过能慢到70多秒

> 没有复现你所说的情况，请详细说明你怎么测试，系统、内存、及各种参数配置。

**Comment by 13718413797** [comment]
> 没有复现你所说的情况，请详细说明你怎么测试，系统、内存、及各种参数配置。

**Comment by 13718413797** [comment]
同样的图片一直请求
![image](https://user-images.githubusercontent.com/20590467/60255766-f28fb780-9902-11e9-921b-1757e670dadf.png)

**Comment by wenlihaoyu** [comment]
不管测试多少次结果应该都是一样，不会出现像你这样的波动。可以检查你部署的Flask服务是否有问题，本项目是用的web.py。建议你可以后台跑一下，比如循环100次，看每次消耗时间是否和Flask服务一致，如果不一致，肯定就是你部署的服务有问题。

**Comment by 13718413797** [comment]
把flask换成web.py可以了  果然是flask出了问题,卡了2天了,一直以为是tf的graph出了问题.谢谢大神指点,万分感谢
