### ISSUE TITLE
install succed.use RTX2080 cuda10 tensorflow 1.13 

### ISSUE THREAD

**Issue by bing1zhi2** [chineseocr/chineseocr#287]
first I  use RTX2080 and cuda9, tf 1.8,  I installed successful, but when I run  the app.py to test on a pic,an error occur :
RuntimeError: cublas runtime error : the GPU program failed to execute at

After I changed to cuda10 and tf.1.4 ,there is another error :

`tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: You must feed a value for placeholder tensor 'Placeholder_368' with dtype float and shape [2]
	 [[{{node Placeholder_368}}]]
	 [[strided_slice_10/_2295]]
  (1) Invalid argument: You must feed a value for placeholder tensor 'Placeholder_368' with dtype float and shape [2]
	 [[{{node Placeholder_368}}]]
0 successful operations.
0 derived errors ignored`

seems the version of tf is not right.so I changed to tf 1.13 ,  and it works althrough it says many function is deprecated.

**Comment by zyjcs** [comment]
how  do you  solve this problem ？ thanks  for your reply.
