### ISSUE TITLE
我有多张显卡如何充分利用？

### ISSUE THREAD

**Issue by StringKe** [chineseocr/chineseocr#289]
1. 在识别的时候我的显卡0是在使用的 配置GPUID=0,1 另外的那种显卡还是没有工作
2. torch 在识别了600多张之后经常报出显存不足，是没有释放之前识别的数据么？我的darknet没有出现这个问题

**Comment by wenlihaoyu** [comment]
识别只支持单卡，单卡已足够。你如果文字检测用的是keras，可以限制tf的显存使用量，tf默认会占满整张显卡，那么pytorch自然没有显卡可用。

**Comment by StringKe** [comment]
@wenlihaoyu 如何支持新版本的ts和nvidia驱动，使用gpu docker

**Comment by StringKe** [comment]
我大概有120w的图片需要识别内容，有双卡要合理的利用并优化速度
