### ISSUE TITLE
crnn.pytorch's result is correct but different from chineseocr

### ISSUE THREAD

**Issue by Aurora11111** [chineseocr/chineseocr#29]

**Comment by wenlihaoyu** [comment]
crnn.pytorch只支持英文的吧，你需要替换chineseocr 项目crnn 目录下key.py文件为你训练的字符集

**Comment by Aurora11111** [comment]
我替换了的,我先训练的全是数字的，生出的crnn.pth放到chineseocr里面识别结果也是数字，但是不正确．顺便问一下，crnn.pytorch 不可以训练中文吗？

**Comment by wenlihaoyu** [comment]
可以训练中文，你在chineseocr项目里面测试单行文字识别，肯定有一些问题。chineseocr项目还需要先对对图像文字定位检测，因为anchors的问题，输入图像太小，就检测不到，所以你就得不到识别结果哈
