### ISSUE TITLE
为何准确率这么低？

### ISSUE THREAD

**Issue by Liuxiang0358** [chineseocr/chineseocr#296]
您好，我在  train/ocr/train-ocr.ipynb  按照当前步骤训练时训练收敛速度很慢，batch_size =128,
alphabetChinese = '帐捷勇翔猜萃洞灯报掀缕五减步题 。。。。’ 这里改为了labell去重的字符，
用的自己的2.7G的一个数据集，是我训练的时间太少了吗？

epoch:0/10
7032/7032 [==============================] - 1351s 192ms/step - loss: 0.6181 - acc: 4.8842e-04
epoch:1/10
7032/7032 [==============================] - 1356s 193ms/step - loss: 0.0117 - acc: 9.7670e-04
epoch:2/10
7032/7032 [==============================] - 1357s 193ms/step - loss: 0.0096 - acc: 0.0024
epoch:3/10
7032/7032 [==============================] - 1355s 193ms/step - loss: 0.0087 - acc: 0.0039
epoch:4/10
7032/7032 [==============================] - 1356s 193ms/step - loss: 0.0082 - acc: 0.0039
epoch:5/10
7032/7032 [==============================] - 1353s 192ms/step - loss: 0.0079 - acc: 0.0039
epoch:6/10
7032/7032 [==============================] - 1354s 193ms/step - loss: 0.0077 - acc: 0.0049
epoch:7/10
7032/7032 [==============================] - 1356s 193ms/step - loss: 0.0075 - acc: 0.0049
epoch:8/10
7032/7032 [==============================] - 1355s 193ms/step - loss: 0.0074 - acc: 0.0083
epoch:9/10
7032/7032 [==============================] - 1355s 193ms/step - loss: 0.0073 - acc: 0.0107

**Comment by wenlihaoyu** [comment]
检测你数据及代码是否有问题哈，alphabetChinese字符集这么小，几次迭代应该就收敛了。

**Comment by 305863162** [comment]
@Liuxiang0358 请问您运行 train/ocr/train-ocr.ipynb  文件报错了吗？我这边各种问题,小白请教怎么可以顺利运行？

**Comment by xavier1001** [comment]
> 请问您运行 train/ocr/train-ocr.ipynb 文件报错了吗？我这边各种问题,小白请教怎么可以顺利运行？

@305863162 请问顺利运行了吗？我这边也是好多问题，解决了一部分，有一个问题卡了

**Comment by xavier1001** [comment]
> 您好，我在 train/ocr/train-ocr.ipynb 按照当前步骤训练时训练收敛速度很慢，batch_size =128,
> alphabetChinese = '帐捷勇翔猜萃洞灯报掀缕五减步题 。。。。’ 这里改为了labell去重的字符，
> 用的自己的2.7G的一个数据集，是我训练的时间太少了吗？

@Liuxiang0358 请问您怎么解决的啊？我acc一直是0，求指点

**Comment by pekinghk** [comment]
可以看下这个 https://github.com/chineseocr/chineseocr/issues/498
希望可以帮助到你
