### ISSUE TITLE
pytorch 用自己的数据训练后倒入出错，怀疑是最后模型参数改变的问题？（训练的为327W的数据集）

### ISSUE THREAD

**Issue by Liuxiang0358** [chineseocr/chineseocr#299]
import os
GPUID='0'##调用GPU序号
os.environ["CUDA_VISIBLE_DEVICES"] = GPUID
import torch
from apphelper.image import xy_rotate_box,box_rotate,solve
import model

RuntimeError                              Traceback (most recent call last)
<ipython-input-4-19623bc780ae> in <module>()
      4 import torch
      5 from apphelper.image import xy_rotate_box,box_rotate,solve
----> 6 import model

~/downlowm/chineseocr_train/model.py in <module>()
      6 
      7 if ocrFlag=='torch':
----> 8     from crnn.crnn_torch import crnnOcr as crnnOcr ##torch版本ocr
      9 elif ocrFlag=='keras':
     10      from crnn.crnn_keras import crnnOcr as crnnOcr ##keras版本OCR

~/downlowm/chineseocr_train/crnn/crnn_torch.py in <module>()
     36 
     37 ##加载模型
---> 38 model,converter = crnnSource()
     39 model.eval()
     40 def crnnOcr(image):

~/downlowm/chineseocr_train/crnn/crnn_torch.py in crnnSource()
     31     # load params
     32 
---> 33     model.load_state_dict(modelWeights)
     34 
     35     return model,converter

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
    775         if len(error_msgs) > 0:
    776             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
--> 777                                self.__class__.__name__, "\n\t".join(error_msgs)))
    778         return _IncompatibleKeys(missing_keys, unexpected_keys)
    779 

RuntimeError: Error(s) in loading state_dict for CRNN:
	size mismatch for rnn.1.embedding.weight: copying a param with shape torch.Size([5990, 512]) from checkpoint, the shape in current model is torch.Size([5530, 512]).
	size mismatch for rnn.1.embedding.bias: copying a param with shape torch.Size([5990]) from checkpoint, the shape in current model is torch.Size([5530]).

**Comment by Onebing** [comment]
请问这个问题怎么解决的

**Comment by Onebing** [comment]
请问这个问题怎么解决的
