### ISSUE TITLE
alphabetChinese 训练的的数据能使用汉字吗

### ISSUE THREAD

**Issue by Onebing** [chineseocr/chineseocr#305]
我看训练数据现在代码不支持汉字，您是怎么进行训练的。

**Comment by Onebing** [comment]
alphabetChinese = u'\'疗绚诚娇溜题贿者廖更纳加奉公。。。
alphabet = '1234567890abcd 
我增加了两个变量之后进行合并，现在就是训练的数据比较麻烦

**Comment by Onebing** [comment]
我做了一个增值税发票识别的 但是整体效果不如百度的是别的  得重新训练一下

**Comment by wenlihaoyu** [comment]
alphabet替换为你需要训练的字符即可

**Comment by Onebing** [comment]
> 字母替换为你需要训练的字符即可

收到，谢谢您的回复

**Comment by gydlcc** [comment]
你那个发票的识别怎么样，有项目地址吗

**Comment by MEGALO-JOE** [comment]
如何增加alphabetChinese里面的中文并训练？
