### ISSUE TITLE
我在单独选练CRNN出现了问题？(我使用自己的数据集进行训练出现问题，但是当我使用360W数据集时一切正常），是不是我数据集格式问题？？？)

### ISSUE THREAD

**Issue by Liuxiang0358** [chineseocr/chineseocr#311]
nepochs = 10
acc  = 0

interval = len(train_loader)//2##评估模型

            
for i in range(nepochs):
    print('epoch:{}/{}'.format(i,nepochs))
    n = len(train_loader)
    pbar = Progbar(target=n)
    train_iter = iter(train_loader)
    loss = 0
    for j in range(n):
        for p in model.named_parameters():
            p[1].requires_grad = True
            if 'rnn.1.embedding' in p[0]:
                p[1].requires_grad = True
            else:
                p[1].requires_grad = False##冻结模型层

        model.train()
        cpu_images, cpu_texts = train_iter.next()
        cost = trainBatch(model, criterion, optimizer,cpu_images, cpu_texts)

        loss += cost.data.numpy()
        
        if (j+1)%interval==0:
            curAcc = val(model, testdataset, max_iter=1024)
            if curAcc>acc:
                acc = curAcc
                torch.save(model.state_dict(), '/home/lab507c/downlowm/chineseocr_train/train/ocr/modellstm.pth')
            
               
        pbar.update(j+1,values=[('loss',loss/((j+1)*batchSize)),('acc',acc)])

TypeError                                 Traceback (most recent call last)
<ipython-input-22-75a43265c459> in <module>()
     20 
     21         model.train()
---> 22         cpu_images, cpu_texts = train_iter.next()
     23         cost = trainBatch(model, criterion, optimizer,cpu_images, cpu_texts)
     24 

~/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    580                 self.reorder_dict[idx] = batch
    581                 continue
--> 582             return self._process_next_batch(batch)
    583 
    584     next = __next__  # Python 2 compatibility

~/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _process_next_batch(self, batch)
    606                 raise Exception("KeyError:" + batch.exc_msg)
    607             else:
--> 608                 raise batch.exc_type(batch.exc_msg)
    609         return batch
    610 

TypeError: function takes exactly 5 arguments (1 given)

**Comment by AnaZou** [comment]
将DataLoader中的num_workers参数设置为0．
