### ISSUE TITLE
为什么用ocr/train-ocr.ipynb 进行迁移学习识别率较低?

### ISSUE THREAD

**Issue by wenston2006** [chineseocr/chineseocr#321]
@wenlihaoyu  你好,感谢你的代码;我在采用ocr/train-ocr.ipynb进行迁移学习时,发现识别率不高;此时我只用了2,3万张自己场景下的文字图片; 但如果我再额外加入百万张合成的图片,此时训练的模型识别率较高(相当于从头开始训练);  而且这两种情况下,刚开始训练的文字识别率都是从0逐渐升高的; 我之前有过人脸识别模型的训练经验, 人脸模型进行迁移学习时,刚开始训练的识别率不至于从0开始;请问这是什么原因? 在某些场景下,可能没法把全部训练图片上传到服务器上训练,这时只能进行迁移学习; 但这样迁移学习的模型识别率却不够高

**Comment by wenlihaoyu** [comment]
人脸识别是分类，不训练模型准确率就是1/N；ocr是序列识别，一张图片所有字符识别正确才算正确，两个都不在同一范畴。

**Comment by wenston2006** [comment]
了解了,谢谢

**Comment by wenston2006** [comment]
@wenlihaoyu  有没有尝试过加入attention 机制? 我尝试了github上几个版本,多数都容易过拟合; 不知是不是训练数据用的不够多还是训练有些技巧;tensorflow 自带的版本训练也比较复杂,对显存大小要求较高.

**Comment by 305863162** [comment]
@wenston2006  您好,请教下,运行 train-ocr.ipynb模型文件问题,目前是各种报错,可以指导下吗？新手感谢。
