### ISSUE TITLE
我需要专门对中文进行识别，我该如何使用train_ocr实现CNN+CTC呢，能在在以训练的模型上进行迁移学习？

### ISSUE THREAD

**Issue by Liuxiang0358** [chineseocr/chineseocr#326]

**Comment by wenston2006** [comment]
train-ocr.py的代码里面已经实现了迁移学习; 文字识别做迁移学习跟一般的分类任务不一样, 最好多放些训练数据; 否则效果不会很理想

**Comment by Liuxiang0358** [comment]
请问我该怎么整理数据呢，有一些字符老是识别不出来，只是简单的加进去的话会比较难收敛？

**Comment by wenston2006** [comment]
要保证大多数训练数据是定长的,这个作者在别的issue里面提到了; 另外可以查看一下识别不出来的字符是否在5990.txt那个字符集里面, 如果不在可以添加到5990.txt里面;

**Comment by Liuxiang0358** [comment]
好的，谢谢！

**Comment by GandalfLiu** [comment]
> 要保证大多数训练数据是定长的,这个作者在别的issue里面提到了; 另外可以查看一下识别不出来的字符是否在5990.txt那个字符集里面, 如果不在可以添加到5990.txt里面;

5990.txt有这个文件么

**Comment by MTCai** [comment]
项目里没有train_ocr.py，你们方便发一份吗？

**Comment by pekinghk** [comment]
> 项目里没有train_ocr.py，你们方便发一份吗？

在master分支
