### ISSUE TITLE
文字稍微大一点就会不准确？

### ISSUE THREAD

**Issue by GandalfLiu** [chineseocr/chineseocr#330]
非常感谢大牛提供的开源项目，这个项目在其它图片上表现非常好， 但是在在字体稍微大一点的图片上却不尽如人意， 有什么调试的方法么？
![~6BVYJ IX`4ZZXW~XO}2}_D](https://user-images.githubusercontent.com/42861671/63246340-0c130700-c295-11e9-9425-93845ae5be5a.png)
![4B NL`1(@RFQIVW)C8G}Q9W](https://user-images.githubusercontent.com/42861671/63246603-a2472d00-c295-11e9-8269-d3fe0fc2c42a.png)

**Comment by GandalfLiu** [comment]
![~6BVYJ IX`4ZZXW~XO}2}_D](https://user-images.githubusercontent.com/42861671/63246729-e63a3200-c295-11e9-91c7-92b8cfc8fb21.png)

**Comment by GandalfLiu** [comment]
大概是文字超过60、70像素之后准确率会急剧下降

**Comment by foreseez** [comment]
> 大概是文字超过60、70像素之后准确率会急剧下降

老哥能留个你的qq吗 请教一下实现问题。多谢  或者你加我   1136899882

**Comment by GandalfLiu** [comment]
已解决， 在config.py中有个IMGSIZE配置成1024，  准确率提升
