### ISSUE TITLE
运行完后没有出现结果是怎么回事？大佬们走过路过来看看啊 

### ISSUE THREAD

**Issue by foreseez** [chineseocr/chineseocr#332]
![image](https://user-images.githubusercontent.com/18757695/63313111-fdc8f780-c335-11e9-9570-153c6d60e5fc.png)
`环境是win10 在本地跑的  在命令行终端运行完后没有出现结果，也上传了图片的  环境是anaconda python3.6  需要的环境也配置了   模型文件也上传了  大佬们看看啊 `

**Comment by zyjcs** [comment]
环境是win10 在本地跑的 在命令行终端运行完后没有出现结果，也上传了图片的 环境是anaconda python3.6 需要的环境也配置了 模型文件也上传了 大佬们看看啊

**Comment by zyjcs** [comment]
![文字识别demo](https://user-images.githubusercontent.com/18757695/63313237-5bf5da80-c336-11e9-8485-7df56a51878f.png)

**Comment by zyjcs** [comment]
上传图片之后 终端的代码没有变化呢  我是在anconda prompt 里面运行的代码

**Comment by zyjcs** [comment]
有知道的大佬可以加下q吗  1136899882

**Comment by zyjcs** [comment]
本地没有GPU

**Comment by zyjcs** [comment]
return tocall(*args)
  File "D:\pycharm\chineseocr\app.py", line 91, in POST
    res = trainTicket.trainTicket(result)
  File "D:\pycharm\chineseocr\application\trainTicket.py", line 14, in __init__
    self.station()
  File "D:\pycharm\chineseocr\application\trainTicket.py", line 33, in station
    station['出发'],station['到达'] = res[0][0].replace('站',''),res[0][1].replace('站','')
IndexError: list index out of range


运行火车票 出现这个 是不是数组越界错误啊
