### ISSUE TITLE
cpu 模式一个很奇怪的现象，请教一下

### ISSUE THREAD

**Issue by bltcn** [chineseocr/chineseocr#339]
非常感谢作者，工程的完整性很高，我是在win 10的wsl环境下，ubuntu 18.04 lts版本下部署的，用的是app分支，修改了app.py里面137行的TIMEOUT变量未定义的问题，然后就开始运行了（我没有注意到config.py里面还有一个gpu定义），刚开始试了几个都很正常，我还特意测试了一下把图片180度反转看看能否正确返回，基本都在20s以内返回结果，下面奇怪的事情来了，我想修改一下返回结果，把文字检测的角度angel也一起返回，结果就好像死机了一样，死活不出结果了，我把代码还原之后，也还是不行，我把config.py里面的GPU设置为false，也不行了，想请教一下，可能是什么原因？
环境：Windows 10 专业版 64-bit (10.0, Build 18362) (18362.19h1_release.190318-1202)
ubuntu 18.04lts
Python 3.6.9 :: Anaconda, Inc.
conda 4.7.11

**Comment by bltcn** [comment]
发现原因了，可能是之前某次没等执行完，就停掉了，导致file.lock文件没删除，然后进入死循环了

**Comment by wenlihaoyu** [comment]
参数不用修改，没有GPU默认会启动CPU执行。TIMEOUT已经添加到config文件。file.lock文件问题也修复

**Comment by bltcn** [comment]
你改的逻辑不太对，我明白你的意思是为了防止重入，但实际上你的代码不能解决这个问题，而且我测试了一下多个请求同时发起也没什么问题，给你参考一下我的修改，另外，我建议最好把检测角度、检测文本所在位置以及最终的识别都分开提供api，这样会更好用一些。我最近会修改一下，如果你没来得及，我可以提供我修改后的版本给你
[app.zip](https://github.com/chineseocr/chineseocr/files/3540519/app.zip)

**Comment by linsng** [comment]
请问这个问题有修复吗
![1F0EB45B-2C6A-4172-ACBE-60050AA370B9](https://user-images.githubusercontent.com/29528786/87846547-405ad180-c903-11ea-85fe-4b93d864d981.png)
