### ISSUE TITLE
Couldn't open file: ../chineseocr/models/text.names

### ISSUE THREAD

**Issue by JiaoPaner** [chineseocr/chineseocr#34]
ipython app.py 8080
报错:
Loading weights from /root/ocr/chineseocr/models/text.weights...Done!
Couldn't open file: ../chineseocr/models/text.names
text.names和text.weights都在models文件夹下 却报无法读取text.names
请问:读取这个文件的代码应该改哪里

**Comment by Aurora11111** [comment]
你应该下载原来的text.names放进去

**Comment by JiaoPaner** [comment]
感谢 我把models里的所有文件都复制过去了... 
text.data要用代码仓库里的text.data 而不是下载models里的text.data

**Comment by xxllp** [comment]
可怕啊
