### ISSUE TITLE
使用docker运行会报错 'ascii' codec can't decode byte 0xe6 in position 854: ordinal not in range(128)

### ISSUE THREAD

**Issue by Alon-SOL** [chineseocr/chineseocr#353]
使用dockerfile创建docker后，运行app.py ，发送请求的时候报ascii码的错误，有谁知道怎么解决吗

**Comment by wenlihaoyu** [comment]
系统缺少对中文的支持，在Dockerfile文件加入 ENV LANG C.UTF-8

**Comment by Alon-SOL** [comment]
> 系统缺少对中文的支持，在Dockerfile文件加入ENV LANG C.UTF-8
