### ISSUE TITLE
运行app.py时，使用不含文字的图片时会报错ValueError

### ISSUE THREAD

**Issue by PuddingCoder** [chineseocr/chineseocr#359]
ValueError: not enough values to unpack (expected 2, got 0)

OCR使用torch模型

**Comment by PuddingCoder** [comment]
`main.TextOcrModel#model() `
在这个函数调用`detect_box()`后对输出的`boxes`或`scores`做个长度判断即可。

**Comment by luoqishuai** [comment]
可是有时候,boxes scores size不为0的时候也会报错
![图片](https://user-images.githubusercontent.com/40172595/69136222-6e2e1300-0af5-11ea-93da-cdc878f6adee.png)

**Comment by PuddingCoder** [comment]
> 可是有时候,boxes scores size不为0的时候也会报错
> ![图片](https://user-images.githubusercontent.com/40172595/69136222-6e2e1300-0af5-11ea-93da-cdc878f6adee.png)

可能因为后面的`self.box_cluster(img,boxes,scores,**args)`里调用`textdetector.detect()`过滤了不符合规则的box scores，可能把所有的box和scores全部过滤，所以需要改下里面的逻辑，做一些为空判断，要改个两处吧大概，不难。

**Comment by xiaomimi3456** [comment]
如下可以解决： 
   def detect(self, text_proposals,scores,size,
               TEXT_PROPOSALS_MIN_SCORE=0.7,
               TEXT_PROPOSALS_NMS_THRESH=0.3,
               TEXT_LINE_NMS_THRESH = 0.3,
               LINE_MIN_SCORE=0.8
               ):
        """
        Detecting texts from an image
        :return: the bounding boxes of the detected texts
        @@param:TEXT_PROPOSALS_MIN_SCORE:TEXT_PROPOSALS_MIN_SCORE=0.7##过滤字符box阀值
        @@param:TEXT_PROPOSALS_NMS_THRESH:TEXT_PROPOSALS_NMS_THRESH=0.3##nms过滤重复字符box
        @@param:TEXT_LINE_NMS_THRESH:TEXT_LINE_NMS_THRESH=0.3##nms过滤行文本重复过滤阀值
        @@param:LINE_MIN_SCORE:##行文本置信度
        
        """
        # pdb.set_trace()
        #text_proposals, scores=self.text_proposal_detector.detect(im, cfg.MEAN)
        keep_inds=np.where(scores>TEXT_PROPOSALS_MIN_SCORE)[0]### 
        text_proposals, scores=text_proposals[keep_inds], scores[keep_inds]
        sorted_indices=np.argsort(scores.ravel())[::-1]
        text_proposals, scores=text_proposals[sorted_indices], scores[sorted_indices]

        # nms for text proposals
        if len(text_proposals)>0:
            text_proposals, scores = nms(text_proposals,scores,TEXT_PROPOSALS_MIN_SCORE,TEXT_PROPOSALS_NMS_THRESH)
            scores=normalize(scores)            
            text_lines,scores = self.text_proposal_connector.get_text_lines(text_proposals, scores, size)##合并文本行
            text_lines = get_boxes(text_lines)
            text_lines, scores = rotate_nms(text_lines,scores,LINE_MIN_SCORE,TEXT_LINE_NMS_THRESH)
            
            return text_lines,scores
        else:
            return [], []
