### ISSUE TITLE
crnn pytorch模型文件转换成keras的模型文件 predict结果不对

### ISSUE THREAD

**Issue by jewelcai** [chineseocr/chineseocr#360]
利用pytorch_to_keras.py将模型文件转换为keras的h5文件之后，不含lstm的模型效果还可以，但是含lstm的模型，预测结果完全是错误的。
请问有谁碰到这个问题嘛？
<img width="511" alt="屏幕快照 2019-09-20 上午10 27 38" src="https://user-images.githubusercontent.com/8166517/65294551-5a1b7300-db91-11e9-8cda-cd6d7837f246.png">

**Comment by jewelcai** [comment]
这个是相同脚本转换的不含lstm层的模型文件的predict的结果
<img width="517" alt="屏幕快照 2019-09-20 上午10 31 42" src="https://user-images.githubusercontent.com/8166517/65294802-eb8ae500-db91-11e9-92cf-3a0d8f1150b2.png">

**Comment by wenlihaoyu** [comment]
转换代码要加 -lstm参数 
python tools/pytorch_to_keras.py  -weights_path models/ocr-lstm.pth -output_path models/ocr-lstm  -lstm True

允许测试修改对应的config文件，LSTMFLAG = True，ocrFlag = 'keras'

**Comment by jewelcai** [comment]
> 转换代码要加 -lstm参数
> python tools/pytorch_to_keras.py -weights_path models/ocr-lstm.pth -output_path models/ocr-lstm -lstm True
> 
> 允许测试修改对应的config文件，LSTMFLAG = True，ocrFlag = 'keras'

谢谢回复。 我在原工程下按这个方法试了一下。结果还是类似：
不知道是不是我什么地方配置错了？
<img width="1072" alt="屏幕快照 2019-09-20 上午11 04 40" src="https://user-images.githubusercontent.com/8166517/65296264-7837a200-db96-11e9-89dc-aa77af0c2d15.png">
<img width="486" alt="屏幕快照 2019-09-20 上午11 05 14" src="https://user-images.githubusercontent.com/8166517/65296287-8980ae80-db96-11e9-9277-680d9761daa3.png">
<img width="634" alt="屏幕快照 2019-09-20 上午11 05 30" src="https://user-images.githubusercontent.com/8166517/65296304-96050700-db96-11e9-8506-210e586eaa36.png">

执行的指令是这个： python tools/pytorch_to_keras.py  -weights_path models/ocr-lstm.pth -output_path models/ocr-lstm.h5
脚本中的lstm flag defualt已经置成True了

**Comment by jewelcai** [comment]
> 转换代码要加 -lstm参数
> python tools/pytorch_to_keras.py -weights_path models/ocr-lstm.pth -output_path models/ocr-lstm -lstm True
> 
> 允许测试修改对应的config文件，LSTMFLAG = True，ocrFlag = 'keras'

请问您有转换完测试成功的模型文件可以分享嘛？

**Comment by pekinghk** [comment]
> > 转换代码要加-lstm参数
> > python tools / pytorch_to_keras.py -weights_path models / ocr-lstm.pth -output_path models / ocr-lstm -lstm True
> > 允许测试修改对应的配置文件，LSTMFLAG = True，ocrFlag ='keras'
> 
> 谢谢回复。我在原工程下按这个方法试了一下。结果还是类似：
> 不知道是不是我什么地方配置错了？
> <img alt="屏幕快照2019-09-20上午11 04 40" width="1072" src="https://user-images.githubusercontent.com/8166517/65296264-7837a200-db96-11e9-89dc-aa77af0c2d15.png">
> <img alt="屏幕快照2019-09-20上午11 05 14" width="486" src="https://user-images.githubusercontent.com/8166517/65296287-8980ae80-db96-11e9-9277-680d9761daa3.png">
> <img alt="屏幕快照2019-09-20上午11 05 30" width="634" src="https://user-images.githubusercontent.com/8166517/65296304-96050700-db96-11e9-8506-210e586eaa36.png">
> 
> 执行的指令是这个：python tools / pytorch_to_keras.py -weights_path models / ocr-lstm.pth -output_path models / ocr-lstm.h5脚本
> 中的lstm flag defualt已经置成True了

我也发现了这个问题，这个问题的原因作者在network_keras.py文件中CRNN类初始化的时候，leakyRelu的值被附上了lstmFlag的值，修改一下这里就可以正确预测。

**Comment by MagicianQi** [comment]
> > > 转换代码要加-lstm参数
> > > python tools / pytorch_to_keras.py -weights_path models / ocr-lstm.pth -output_path models / ocr-lstm -lstm True
> > > 允许测试修改对应的配置文件，LSTMFLAG = True，ocrFlag ='keras'
> > 
> > 
> > 谢谢回复。我在原工程下按这个方法试了一下。结果还是类似：
> > 不知道是不是我什么地方配置错了？
> > <img alt="屏幕快照2019-09-20上午11 04 40" width="1072" src="https://user-images.githubusercontent.com/8166517/65296264-7837a200-db96-11e9-89dc-aa77af0c2d15.png">
> > <img alt="屏幕快照2019-09-20上午11 05 14" width="486" src="https://user-images.githubusercontent.com/8166517/65296287-8980ae80-db96-11e9-9277-680d9761daa3.png">
> > <img alt="屏幕快照2019-09-20上午11 05 30" width="634" src="https://user-images.githubusercontent.com/8166517/65296304-96050700-db96-11e9-8506-210e586eaa36.png">
> > 执行的指令是这个：python tools / pytorch_to_keras.py -weights_path models / ocr-lstm.pth -output_path models / ocr-lstm.h5脚本
> > 中的lstm flag defualt已经置成True了
> 
> 我也发现了这个问题，这个问题的原因作者在network_keras.py文件中CRNN类初始化的时候，leakyRelu的值被附上了lstmFlag的值，修改一下这里就可以正确预测。

试过了，是可以的。

**Comment by jewelcai** [comment]
> > > 转换代码要加-lstm参数
> > > python tools / pytorch_to_keras.py -weights_path models / ocr-lstm.pth -output_path models / ocr-lstm -lstm True
> > > 允许测试修改对应的配置文件，LSTMFLAG = True，ocrFlag ='keras'
> > 
> > 
> > 谢谢回复。我在原工程下按这个方法试了一下。结果还是类似：
> > 不知道是不是我什么地方配置错了？
> > <img alt="屏幕快照2019-09-20上午11 04 40" width="1072" src="https://user-images.githubusercontent.com/8166517/65296264-7837a200-db96-11e9-89dc-aa77af0c2d15.png">
> > <img alt="屏幕快照2019-09-20上午11 05 14" width="486" src="https://user-images.githubusercontent.com/8166517/65296287-8980ae80-db96-11e9-9277-680d9761daa3.png">
> > <img alt="屏幕快照2019-09-20上午11 05 30" width="634" src="https://user-images.githubusercontent.com/8166517/65296304-96050700-db96-11e9-8506-210e586eaa36.png">
> > 执行的指令是这个：python tools / pytorch_to_keras.py -weights_path models / ocr-lstm.pth -output_path models / ocr-lstm.h5脚本
> > 中的lstm flag defualt已经置成True了
> 
> 我也发现了这个问题，这个问题的原因作者在network_keras.py文件中CRNN类初始化的时候，leakyRelu的值被附上了lstmFlag的值，修改一下这里就可以正确预测。

真是没注意到这个问题。太感谢了~~

**Comment by robbebluecp** [comment]
crnn/network_keras.py 的99行，leakyRelu=lstmFlag改为leakyRelu=leakyRelu,bingo

**Comment by guanshuicheng** [comment]
我关闭了调用角度矫正的模型读入，解决了这个问题。

**Comment by zlszhonglongshen** [comment]
@jewelcai  你好 能分享一下 转换后的ocr-lstm.h5模型吗 1366143083@qq.com  xiexie

**Comment by zlszhonglongshen** [comment]
> @jewelcai 你好 能分享一下 转换后的ocr-lstm.h5模型吗 [1366143083@qq.com](mailto:1366143083@qq.com) xiexie
可以了，原来是需要替换代码。而不是在转模型的时候用。

**Comment by zlszhonglongshen** [comment]
@jewelcai 你好，还是想问下，通过转换后的代码，你测试过自己的数据集，表现的如何？

**Comment by jewelcai** [comment]
> @jewelcai 你好，还是想问下，通过转换后的代码，你测试过自己的数据集，表现的如何？

还可以 能接受  具体指标我没测试

**Comment by simmerken** [comment]
@jewelcai  您好,我在执行转换脚本的时候报如下错误,请问您有没有遇见? 如何解决呢?
loading weights...
weights header:  0 2 0 [320000]
creating keras model...
Parsing Darknet config.
+ 1 conv2d   leaky (3, 3, 3, 64)
Traceback (most recent call last):
  File "test.py", line 295, in <module>
    main()
  File "test.py", line 288, in main
    layers_fun[type](block)
  File "test.py", line 172, in conv
    padding=padding))(self.prev_layer)
  File "/home/jfli/.local/lib/python3.6/site-packages/keras/engine/base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/home/jfli/.local/lib/python3.6/site-packages/keras/layers/convolutional.py", line 132, in build
    raise ValueError('The channel dimension of the inputs '
ValueError: The channel dimension of the inputs should be defined. Found `None`.

**Comment by amandazw** [comment]
请问各位有尝试过将这个crnn转成pb吗？我按照上面的操作转h5成功了，但是转pb出来推理就是中文乱码。
