### ISSUE TITLE
训练时验证集精度较高, 训练完后重新在验证集上测试, 精度下降了7,8个百分点

### ISSUE THREAD

**Issue by wenston2006** [chineseocr/chineseocr#366]
@wenlihaoyu  训练时每隔2000次会将验证集上测试的精度与最佳精度比较,如果当前测试精度更高,则更新最佳精度并保存模型; 在训练过程中,最佳精度达到了87%; 但训练完后, 在验证集上重新测试, 精度下降了7,8个百分点; 请问在单独做测试时, 加载模型是否跟训练时有什么不同?

**Comment by wenston2006** [comment]
找到原因了, 我在重新测试时, 测试集用的另一个; 但感觉目前保存最佳模型的方式对测试集依赖较大, 换一个测试集, 效果下降较大

**Comment by wenlihaoyu** [comment]
检验你训练集与测试集是否差异过大

**Comment by wenston2006** [comment]
我改了一下保存模型的方式,现在改为每隔半个epoch就保存一次模型;之前保存模型的方式可能造成在某个验证集合上效果较好,而用到别的数据集上效果变差.
