### ISSUE TITLE
关于识别速度的问题

### ISSUE THREAD

**Issue by jewelcai** [chineseocr/chineseocr#367]
硬件：Tesla P100。
YOLO检测速度很快，但是crnn的识别感觉略慢。如下所示，光识别所有行需要2s左右。而我用另外的densenet模型识别只需要0.45s.  如下图所示(ocr_batch execution time):

请问crnn这个速度正常嘛？大概优化点在哪里  谢谢。
CRNN：
<img width="834" alt="屏幕快照 2019-09-23 下午7 38 30" src="https://user-images.githubusercontent.com/8166517/65422671-bd2f3300-de39-11e9-8d90-f14d33615082.png">

======
Densenet：
打印出的数据是概率。
<img width="875" alt="屏幕快照 2019-09-23 下午7 34 36" src="https://user-images.githubusercontent.com/8166517/65422533-4d20ad00-de39-11e9-9630-889b2d09063e.png">

**Comment by jewelcai** [comment]
有碰到这个问题的嘛？你们predict的时候速度是怎么样呢？
硬件：Tesla P100

**Comment by wenlihaoyu** [comment]
识别速度依赖你的文本行总数，加了LSTM单行imgW<256,大概需要0.05秒，CPU:0.1秒左右，如果文本行太多，部署应用，可以并行，具体可以根据你的GPU及CPU实现最大优化。

**Comment by weilingfeng1996** [comment]
> 识别速度依赖你的文本行总数，加了LSTM单行imgW<256,大概需要0.05秒，CPU:0.1秒左右，如果文本行太多，部署应用，可以并行，具体可以根据你的GPU及CPU实现最大优化。

想问下针对哪个 函数 并行    没找出来

**Comment by yjmm10** [comment]
> 硬件：Tesla P100。
> YOLO检测速度很快，但是crnn的识别感觉略慢。如下所示，光识别所有行需要2s左右。而我用另外的densenet模型识别只需要0.45s. 如下图所示(ocr_batch execution time):
> 
> 请问crnn这个速度正常嘛？大概优化点在哪里 谢谢。
> CRNN：
> <img alt="屏幕快照 2019-09-23 下午7 38 30" width="834" src="https://user-images.githubusercontent.com/8166517/65422671-bd2f3300-de39-11e9-8d90-f14d33615082.png">
> 
> ======
> Densenet：
> 打印出的数据是概率。
> <img alt="屏幕快照 2019-09-23 下午7 34 36" width="875" src="https://user-images.githubusercontent.com/8166517/65422533-4d20ad00-de39-11e9-9630-889b2d09063e.png">

请问下,你用Tesla P100测试A4字大小的识别时间是多少

**Comment by guanshuicheng** [comment]
识别部分有一半以上的时间花在了box角度旋转矫正上了，每个box都会计算角度旋转原图再做切割，作者用的PIL，改用opencv矫正以后速度大大提升，推理部分改成bacth推入，速度也能大大提升。

**Comment by zlszhonglongshen** [comment]
> 识别部分有一半以上的时间花在了box角度旋转矫正上了，每个box都会计算角度旋转原图再做切割，作者用的PIL，改用opencv矫正以后速度大大提升，推理部分改成bacth推入，速度也能大大提升。

能分享一下，rotate_cut_img的函数吗？谢谢

**Comment by zlszhonglongshen** [comment]
> 识别部分有一半以上的时间花在了box角度旋转矫正上了，每个box都会计算角度旋转原图再做切割，作者用的PIL，改用opencv矫正以后速度大大提升，推理部分改成bacth推入，速度也能大大提升。

你好问下，你的batch推入是怎么修改的啊？ 能不能分享一下 1366143083@qq.com
