### ISSUE TITLE
how much datasets need!~ 

### ISSUE THREAD

**Issue by Aurora11111** [chineseocr/chineseocr#37]

**Comment by wenlihaoyu** [comment]
不需要这么多数据，只要你做到字符均衡，大概一两百万数据就够了

**Comment by Aurora11111** [comment]
OK!谢谢

**Comment by ZJU-PLP** [comment]
@Aurora11111 您好,请问一下您是怎样构造数据集训练的啊?貌似作者的代码里面没有训练数据集的代码啊?是网上找其他的crnn项目进行训练吗?但是数据集和作者的不一样啊,例如我想训练液晶数字的,该怎样训练,求告知,非常感谢!

**Comment by black107** [comment]
@wenlihaoyu 请问文字识别的语料怎么得到？怎么保证均衡？还有一张训练图包含多少个字有什么讲究吗？ 期待您的回复～谢谢

**Comment by ZJU-PLP** [comment]
@wenlihaoyu 请教一下如果我要识别这幅图片中的数字,训练时应该注意什么问题呢,为什么我用0~9的电子字体,采用不定长字符训练,acr已经到90%多了,但是实际图片验证效果很差呢?
![004](https://user-images.githubusercontent.com/32757213/45789290-84520080-bcb1-11e8-9110-0aa400b44ab0.jpg)

**Comment by Gavin666Github** [comment]
@ZJU-PLP 兄弟，仪表类数字识别有解决方案吗，数据集怎么搞的，测试效果怎样，我遇到了同样的问题，这个项目识别身份证及印刷字体都ok，但是液晶屏上的汉字数字就识别不到了，求指教

**Comment by ZJU-PLP** [comment]
@Gavin666Github 我最后的识别效果也很差，没有达到理想效果。当时是通过制作不同的实际背景，然后在背景上面生成数字和文字，进行训练，因为我电脑显卡比较差，没有训练起来。
