### ISSUE TITLE
keras执行出错

### ISSUE THREAD

**Issue by robbebluecp** [chineseocr/chineseocr#370]
跟#342 issue类似，keras做ocr无法work

ValueError: Tensor Tensor("time_distributed_2/Reshape_1:0", shape=(?, ?, 5530), dtype=float32) is not an element of this graph.

**Comment by jewelcai** [comment]
https://gist.github.com/jewelcai/8942bdca8352c08f0f1a62e0f3d9ccc8

试试这个  再改改  最好用keras的方法解决

**Comment by robbebluecp** [comment]
已解决，因为默认开启debug模式，关闭即可，如下：
app = web.application(urls, globals(), autoreload=False)
增加 autoreload=False即可
