### ISSUE TITLE
【已解决】用Docker的方式启动不了

### ISSUE THREAD

**Issue by 0000005** [chineseocr/chineseocr#382]
docker image已经创建了，但是就启动不了，也没有日志
![image](https://user-images.githubusercontent.com/9690089/66983477-40ffd680-f0eb-11e9-93fd-4665eca5986c.png)
要怎么解决呢？

**Comment by 0000005** [comment]
换了一台支持avx指令集的机器，docker跑成功了，
但是访问报错
 网页报错如下：
![image](https://user-images.githubusercontent.com/9690089/66989320-bc1aba00-f0f6-11e9-9042-f3057f48238d.png)
docker控制台报错如下：
![image](https://user-images.githubusercontent.com/9690089/66989363-d3f23e00-f0f6-11e9-8aca-c8fef9cc8d06.png)

**Comment by Ariv-theclairvoyant** [comment]
Hello,
Paste the below code in app.py

import _locale
_locale._getdefaultlocale = (lambda *args: ['en_US', 'utf8'])

It should work, try it out.

**Comment by 0000005** [comment]
Thank you! @Ariv-theclairvoyant 
I already solved this problem，by adding "ENV LANG C.UTF-8" to Dockerfile.
