### ISSUE TITLE
关于识别的图片有两种字体的情况

### ISSUE THREAD

**Issue by guowenjia** [chineseocr/chineseocr#40]
您好，我尝试用chineseocr去识别彩票的图片，发现号码的识别非常低，汉字的识别很高，可能是因为彩票上的数字和彩票上的汉字是两种字体，我想知道的是，像彩票这种有两种字体的情况或者多种字体的情况，如何提高识别率？

**Comment by guowenjia** [comment]
我是小白。请问是不是要自己截图，然后做标记？大概需要标记多少数据？

**Comment by wenlihaoyu** [comment]
不用，彩票字体输入常规字体，模型已经训练过。可以调节一些基础参数即可 ，比如MAX_HORIZONTAL_GAP调到80，
![image](https://user-images.githubusercontent.com/7800267/45170560-ba639f00-b232-11e8-9c4c-f6e9afd25486.png)

**Comment by guowenjia** [comment]
@wenlihaoyu 我这里有一张图片，类似这样的
![webwxgetmsgimg 56](https://user-images.githubusercontent.com/27345371/45405465-89052c00-b695-11e8-9bd1-573e8411f2dc.jpeg)
您能帮我看一下这样的图片应该如何调参吗？我这里调整后发现始终号码出不来。谢谢！

**Comment by Aurora11111** [comment]
@wenlihaoyu @guowenjia 类似MAX_HORIZONTAL_GAP(文本行最大间隔值是属于yolo里面的参数吗?那么yolo的训练是用的yolo3 https://github.com/pjreddie/darknet.git这个吗

**Comment by guowenjia** [comment]
我这里还发现一种情况，就是如果每一行数字我按行切出来，基本都能识别正确。我这里想知道有没有办法按行给它切出来，针对数字部分单独实现按行识别?

**Comment by wenlihaoyu** [comment]
@guowenjia 有两种方式可以优化：
第一种，根据识别的部分字符，去做二次检测，例如识别出“单选”字符，那么根据此字符串的坐标，修改此坐标的w为图像的width，然后再调用OCR识别此行即可，或者直接将model.py文件中alph=0.2，alph设置为足够大，比如500。
第二种，修改相关参数，详见（detectors.py）文件，修改MIN_RATIO（字符width/height），默认为1，手动调整为你检测图像集的最优值；TEXT_PROPOSALS_WIDTH(最小字符宽度)，默认是5， 可以调为0.
![image](https://user-images.githubusercontent.com/7800267/45435498-3d796f00-b6e3-11e8-8a18-9a41bb359a7d.png)

**Comment by wenlihaoyu** [comment]
@Aurora11111 这些参数参考了ctpn项目的部分代码 https://github.com/eragonruan/text-detection-ctpn/blob/master/lib/text_connector/detectors.py.

**Comment by guowenjia** [comment]
@wenlihaoyu 非常感谢您！我在修改了alph参数之后(alph=40在我现有的图片集合里面识别最好，之前采用了500)，识别率上明显有了很大的提升。但是我发现在修改alph参数之后，即使修改detectors里面的参数，也对结果没有任何影响。我现在的参数是
```
MAX_HORIZONTAL_GAP=400, MIN_V_OVERLAPS=0.6, MIN_SIZE_SIM=0.6,
TEXT_PROPOSALS_MIN_SCORE=0.2, TEXT_PROPOSALS_NMS_THRESH=0.3,
MIN_RATIO=0.8, TEXT_LINE_NMS_THRESH=0.99, LINE_MIN_SCORE=0.2,
TEXT_PROPOSALS_WIDTH=0, MIN_NUM_PROPOSALS=0, textmodel='opencv_dnn_detect'
```
上面那个彩票中，中间的B的那一行并没有识别出来。我看了一下代码里面切割的数字的图片，发现是如下情况：
![5](https://user-images.githubusercontent.com/27345371/45538695-56e0ff00-b83a-11e8-9b9b-6d61a3a88856.jpg)
![6](https://user-images.githubusercontent.com/27345371/45538700-5a748600-b83a-11e8-87c2-c9cd6ad1218c.jpg)
![7](https://user-images.githubusercontent.com/27345371/45538704-5cd6e000-b83a-11e8-81a0-8517bafe30e8.jpg)
因为A和C做到了很好的切割，所有效果也很好。麻烦您再帮我看看，对于第二行图片的识别情况，还有没有办法通过调参，优化成像A和C那样的？
还有就是我发现只要行切割没有问题，号码识别基本没有问题。所以第二行那个情况，我第一次没有识别到单选，也很难通过切割的方式切出这一行单独的数据。
多谢！

**Comment by wenlihaoyu** [comment]
应该是漏检了，不过你这个是标准的一行一行的识别，其实可以不用yolo3进行文字定位，直接采用传统的分割，就可以得到每一行，然后调用OCR即可。
"""
from scipy.ndimage import filters,interpolation,morphology,measurements,minimum
from pylab import amin, amax
def image_bin(im):
    ##对图像进行0-1处理
    raw = np.array(im.convert('L'))
    image = raw-amin(raw)
    image = image/amax(image)
    m = np.copy(image)
    m = filters.percentile_filter(m,80,size=(20,2))
    m = filters.percentile_filter(m,80,size=(2,20))
    w,h = min(image.shape[1],m.shape[1]),min(image.shape[0],m.shape[0])
    flat = np.clip(image[:h,:w]-m[:h,:w]+1,0,1)
    flat[flat>0.5]=255
    flat[flat<=0.5]=0
    return flat.astype(np.uint8)

"""

"""
def image_split_by(im,axis=1,avg=None):
    #竖直方向切割图片，保留单个字符
    #axis=1 保留行
    #axis=0 保留字符
    #@@im:Image 
    tmpImg = image_bin(im)
    if avg is None:
       avg = tmpImg.mean()
    tmpImg[tmpImg>avg] = 255
    tmpImg[tmpImg<=avg] = 0
    tmpSum = tmpImg.sum(axis=axis)
    avg = tmpSum.mean()
    Max = tmpSum.max()
    tmpSum[tmpSum>avg] = Max
    tmpSum[tmpSum<=avg] = 0
    
    Yindex = np.where(tmpSum==0)[0]
    index = np.diff(Yindex)
    index = np.where(index!=1)[0].tolist()
    IndexList = [[0]]
    for ind in index:
        if len(IndexList[-1])==1:
            i = Yindex[ind]
            j = Yindex[ind+1]
            interval = j-i
            if axis!=0:
              interval = int(interval*0.3)
            else:
                interval=0

            IndexList[-1].append(i+interval)
            #IndexList[-1].append(i)
            IndexList.append([j-interval])
    if len(IndexList[-1])==1:
        IndexList[-1].append(Yindex[-1])
    return IndexList
"""
## test
"""
im = Image.open('test.jpg')
lines = image_split_by(im,axis=1,avg=None)
"""

**Comment by guowenjia** [comment]
@wenlihaoyu 非常感谢您能再次回答。我测试了test这部分代码返回的类似是这样的数据[[0, 93], [105, 201], [314, 433], [439, 480], [486, 544], [571, 625], [632, 639]。这些返回的应该是截取的y的值，而x就是从0到图片的宽度，对吗？当我按这样的数据在原图上进行标记，发现标记之后图片不是很理想，这里我找了一张扫描的图片。如果对图片处理成608*608，调用您给的函数，图片类似这样:
![origin](https://user-images.githubusercontent.com/27345371/45662403-614e1200-bb34-11e8-912b-449c858982f8.jpg)
如果不对图片处理608*608,图片类似这样：
![origin](https://user-images.githubusercontent.com/27345371/45662446-95293780-bb34-11e8-8892-9a2c3ec33b98.jpg)

而原始的crnn截取类似这样:
![origin](https://user-images.githubusercontent.com/27345371/45662601-11bc1600-bb35-11e8-9fda-1abf7e2ac5a9.jpg)
但是我看后面真正截图之后，原始crnn的每一行都给截取出来了。
而使用自己手动切割的，切的是什么样，结果就是什么样，把一行数据切成两行也不会有一个合并的行。
还有就是图片进行0-1处理，这一步图片我也打开看了，类似这样
![21](https://user-images.githubusercontent.com/27345371/45662652-4b8d1c80-bb35-11e8-8538-3edf9370a090.jpg)
我这里也对其他的图片进行了测试，相比crnn,效果都不是太好。请问我这里是否还有其他方法可以提升？
有没有办法把一行切成两行的这种情况合并成一个新的行的方法，类似crnn那样？
还是我只能再借助其他的切割框架来解决这个问题？我现在准备看一下https://github.com/emedvedev/attention-ocr 这个项目，不知道这个会不会对识别文字位置会好一点。
麻烦您能再给我一点建议。谢谢您了！

**Comment by guowenjia** [comment]
@wenlihaoyu 真的非常感谢您。我从您回答的issue里面获得了一些启发。通过对图片本身的一些调整，我的识别率又有了显著的提升。 我接下来也会通过调参的方式来进一步提高识别率。 非常的感谢您！

**Comment by wenlihaoyu** [comment]
行分割的时候，肯定还要做一些后处理，比如行高度过小，应该就舍弃。识别的时候，要根据坐标取原图的图像。
