### ISSUE TITLE
文本位置检测出来后，如何提取需要的信息

### ISSUE THREAD

**Issue by Bourne-M** [chineseocr/chineseocr#407]
例如二代证，检测出那么多文本行，如何确定哪一个位置是姓名，哪一个位置是身份证号码？
请大佬们科普下，谢谢。

**Comment by 13052** [comment]
简单点儿说就是个if else的事儿。

**Comment by Bourne-M** [comment]
> 简单点儿说就是个if else的事儿。

这个也太简单了点吧，能否详细点呢？多谢

**Comment by wenlihaoyu** [comment]
正则匹配。详细参考application目录

**Comment by 13052** [comment]
> > 简单点儿说就是个if else的事儿。
> 
> 这个也太简单了点吧，能否详细点呢？多谢

直接循环所有检测出的文本，如果文本中出现一些关键字，那就根据这一行的位置确定其他信息的位置。
例如某一行出现“姓名”，根据你文本框的大小就可确定你要找的名字就在这个文本框后面

**Comment by Bourne-M** [comment]
@13052 thks，loud and clear
