### ISSUE TITLE
ocr crnn训练报错

### ISSUE THREAD

**Issue by xavier1001** [chineseocr/chineseocr#409]
epoch:0/10
Traceback (most recent call last):
  File "train-ocr.py", line 276, in <module>
    if (j+1)%interval==0:
ZeroDivisionError: integer division or modulo by zero、
执行train-ocr时，报错如上，
这个interval是这样赋值的：interval = len(train_loader)//2，
而train_loader = torch.utils.data.DataLoader(
    traindataset, batch_size=batchSize,
    shuffle=False, sampler=None,
    num_workers=int(workers),
    collate_fn=alignCollate(imgH=imgH, imgW=imgW, keep_ratio=keep_ratio))
使用代码测试的len(train_loader)是0
使用的作者提供的train/data/ocr/0下面的8张图片
请问如何解决？

**Comment by xavier1001** [comment]
已解决   路径问题

**Comment by zfs1993** [comment]
大哥啥问题呀，我把图片路径改成绝对路径了，还是不行呀
