### ISSUE TITLE
执行train-ocr报错

### ISSUE THREAD

**Issue by haohaoma** [chineseocr/chineseocr#416]
epoch:0/10
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-12-d7c7d4cb2ad5> in <module>
     25         loss += cost.data.numpy()
     26 
---> 27         if (j+1)%interval==0:
     28             curAcc = val(model, testdataset, max_iter=1024)
     29             if curAcc>acc:

ZeroDivisionError: integer division or modulo by zero
使用代码测试的len(train_loader)是1 整除2之后变为0
使用的作者提供的train/data/ocr/0下面的8张图片
路径也是正确的
请问如何解决？

**Comment by balabala7776** [comment]
请用你训练ocr是哪个代码
