### ISSUE TITLE
直接通过调用main.py进行ocr，请问如何切换keras和opencv

### ISSUE THREAD

**Issue by Maxhyl** [chineseocr/chineseocr#456]

**Comment by yjmm10** [comment]
> _No description provided._

在config.py里面yoloTextFlag变量可以选择不同模式的文本检测

**Comment by Maxhyl** [comment]
> > _没有提供描述。_
> 
> 在config.py里面yoloTextFlag变量可以选择不同模式的文本检测

没有config.py里面对应的模型，改了模型名字会出现数据维度不匹配的情况
