### ISSUE TITLE
pytorch训练ocr的模型文件.pth是如何转成darknet的.weights/.cfg文件？

### ISSUE THREAD

**Issue by BigPandaCPU** [chineseocr/chineseocr#477]
作者您好，首先非常感谢你将这么好的项目开源出来，让大家一起学习。
        我最近也遇到些问题，就是OCR识别部分速度慢的问题，看了你这项目之后，才知道你训练CRNN模型的时候，去掉了lstm，并且将pytorch训练的ocr模型文件*.pth转成darknet下的.weights/.cfg文件，通过opencv的darknet接口来调用，这样识别的速度的确是快多了。
        我现在想将自己训练的ocr模型文件.pth转成.weights/.cfg文件，你这里面是提供了一个将keras下的yolov3的h5文件转成darknet的.weights/.cfg文件，你那将ocr的h5文件转成darknet的.weights/cfg文件的代码能提供一份吗？感激不尽！！！

**Comment by wenlihaoyu** [comment]
目前没有这样做，darknet-ocr直接用的darknet训练。有另外的小伙伴像这样转换过，可以加这个微信群问一下
![image](https://user-images.githubusercontent.com/7800267/87802813-4f4e6f00-c884-11ea-923f-ff79b0a41cba.png)

**Comment by BigPandaCPU** [comment]
谢谢作者的回答，我后来自己折腾了一下，转成功了。是间接介转换的。过程如下：
第一步：是将pytorch训练的ocr模型转成keras下ocr文件，h5格式的，参考的脚本是作者提供的 pytorch_to_keras.py
第二步：将keras下的ocr模型文件h5格式的，转换成darknet格式的。参考的脚本是作者提供的 keras_to_darknet.py

在转换过程中遇到的问题如下：有两个地方需要注意一下：
1.pytorch->keras 层的名称不匹配：第一步转成出现的问题。由于darknet的ocr模型的结构和pytorch中的ocr结构稍微有一点差别，其中最主要的差别就是 pytroch下最后的全连接层是linear.weight 和 linear.bias，而在keras模型中，用的是1*1的全卷积代替全连接层，所以在使用改脚本的时候，需要将 linear.weight和linear.bias重命名为cnn.conv7.weights和cnn.conv7.bias。相应的权重也要做reshape操作。代码截图如下：修改的是pytorch_to_keras.py

pytorch_to_keras.py文件
![QQ截图20200724154604](https://user-images.githubusercontent.com/25834151/88370569-d6d83880-cdc4-11ea-8e24-d1f119b01cf2.jpg)

2.keras->darknet 过程中：需要调换一下参数的顺序 需要修改network_keras.py文件（否则在转换的过程中，会报参数不匹配）
![QQ截图20200724155539](https://user-images.githubusercontent.com/25834151/88371227-3420b980-cdc6-11ea-8da4-5aefa0d29006.jpg)

补充说明一点：
我这darknet的ocr的cfg文件，用的是作者提供的那个ocr.cfg文件，里面的字典参数用的是5530.我这训练模型是在作者提供的ocr_dense.pth模型基础上进行微调。（该模型去掉了LSTM层）



转的过程中，需要对ocr模型在pytorch、keras和darknet这三种框架下的模型文件非常熟悉。在使用过程中如果遇到问题，自己先读读代码，应该就能够解决了,也祝大家好运。在此非常感谢作者chineseOcr大哥的分享和指导。
