### ISSUE TITLE
Alternative to Baidu

### ISSUE THREAD

**Issue by ghost** [chineseocr/chineseocr#483]
Thanks for this amazing project. But as I am outside china, I cant download the model files.
Could you kindly provide any alternative download link?

p.s :  The google drive link provided by another ticket does not have the h5 files in it.
https://drive.google.com/drive/folders/1vlA6FjvicTt5GKvAfmycP5AlYxm4i9ze

**Comment by wenlihaoyu** [comment]
http://59.110.234.163:9990/static/models/chineseocr/

**Comment by ghost** [comment]
Thanks a lot
