### ISSUE TITLE
选择定长与不定长训练，是否在预测的时候也应该一一对应

### ISSUE THREAD

**Issue by Aurora11111** [chineseocr/chineseocr#49]

**Comment by Aurora11111** [comment]
图片稍后上传，上传出现一些问题

**Comment by wenlihaoyu** [comment]
预测的时候，将imgH=32,本来就是不定长的嘛，你进行多种处理，有什么意义呢？

**Comment by Aurora11111** [comment]
@wenlihaoyu 
我的imgw=100，这样训练出来的模型在crnn-pytorch里面可以识别，在你的chineseocr里面不能识别，想知道是不是否与训练时是否设置定长有关

**Comment by ZJU-PLP** [comment]
@Aurora11111 好像model.py下面可以把参数改一下,你可以试一下.另外,图片上传不了可以试一下本地上传,我的是在crnn-pytorch里面识别效果很差,这个项目里面识别会好一点
![image](https://user-images.githubusercontent.com/32757213/45996497-fcb02b80-c0ce-11e8-94db-d881b3b94d53.png)

**Comment by Aurora11111** [comment]
@ZJU-PLP 你是定长地训练还是，不定长地训练

**Comment by ZJU-PLP** [comment]
@Aurora11111 imgW=100,生成的数据集是不定长的字母,应该属于定长的?

**Comment by Aurora11111** [comment]
@ZJU-PLP 我的也是imgw=100，并且生成数据是一样宽度的．
没明白不定长的训练是怎么回事

**Comment by ZJU-PLP** [comment]
@wenlihaoyu @Aurora11111 同没明白不定长训练.你的对比图能更新一下吗(本issue的第一个问题)@Aurora11111?我想看一下你的对比图是不是和我的很类似

**Comment by Aurora11111** [comment]
@ZJU-PLP 
还是传不上来.
我的总的情况反应来讲就是crnn-pytorch 可以识别我的数据，chineseocr不行

**Comment by Aurora11111** [comment]
@ZJU-PLP 是的

**Comment by ZJU-PLP** [comment]
@Aurora11111 我遇到的情况是小的图片chineseocr不能检测,因为yolo3的anchor size训练时没有设置很小的,大的图片可以检测,看来你的情况应该和我的不一样
![image](https://user-images.githubusercontent.com/32757213/46004834-7273c180-c0e6-11e8-9c59-811cb5768a3d.png)

**Comment by Aurora11111** [comment]
@ZJU-PLP 我试过了，小的大的都不行

**Comment by Aurora11111** [comment]
@wenlihaoyu 我试过可以检测出来box并且是相同的,只是识别的文本内容不对，我发现了在crnn.py里面
1.    
      scale = image.size[1]*1.0 / 32
       w = image.size[0] / scale
       w = int(w)
       transformer = dataset.resizeNormalize((ｗ, 32))
2.   transformer = dataset.resizeNormalize((100, 32))
选择１＋你的模型+上面ocr测试,结果基本正确
选择１＋我的模型+上面ocr测试，结果不正确
选择２＋你的模型+上面ocr测试，结果不正确
选择２＋我的模型+上面ocr测试，结果完全正确

这样意思就是我训练的模型有问题？应该怎么不定长训练

**Comment by Aurora11111** [comment]
之前代理挂了，现在可以传了：
１．
![img_20180921_112037](https://user-images.githubusercontent.com/39044868/46062185-96dda580-c19b-11e8-9982-88345bb6d31a.jpg)
２．
![img_20180921_112052](https://user-images.githubusercontent.com/39044868/46062198-9fce7700-c19b-11e8-8bb7-bfa28f8061a6.jpg)
３．
![img_20180921_112106](https://user-images.githubusercontent.com/39044868/46062207-a6f58500-c19b-11e8-9062-b7f82c8b1477.jpg)
４．
![img_20180921_112118](https://user-images.githubusercontent.com/39044868/46062209-abba3900-c19b-11e8-990e-5aad55a8f97b.jpg)

**Comment by wenlihaoyu** [comment]
@Aurora11111 说明你选择训练的时候，采用ImgW=100，不合理。举一个简单例子，比如你测试的一个图片大小是1024x32，你resize成100x32,那么图像是不是变形了呢？训练中文的话，你可以采用ImgW=256或者512，实际训练图像不足512，那么进行图片补长。

**Comment by Aurora11111** [comment]
@wenlihaoyu 也就是ｉｍgW＝256就可以实现不定长了吗？

**Comment by wenlihaoyu** [comment]
@Aurora11111 模型的表征能力肯定会变强。crnn.pytorch设置定长训练的目的，是因为训练定长的方便，不用做其他后续处理（如果图像是不定长，那么还要进行补长处理，或者将训练数据集进行归类：imgW=0～128为一组，imgW=128～256又为一组等等），而现实生活中几乎不能找到这么多定长的训练集，这个可以根据你的应用场景去调整。imgW其实是和输出最大字符有关系的，nChars = imgW/4-2

**Comment by ZJU-PLP** [comment]
@wenlihaoyu 您好，请教训练多行字符需要注意哪些呢？感觉单行衣服训练得到的模型对多行衣服检测效果比较差呀

**Comment by ZJU-PLP** [comment]
@wenlihaoyu 您好，请教训练多行字符需要注意哪些呢？感觉单行字符训练得到的模型对多行字符检测效果比较差呀

**Comment by dlml** [comment]
@wenlihaoyu  实际业务不会有这么多规整的训练集，比如识别训练，实际业务中可能标签字符长度不定，有可能10,9,8,7这种，不知道你是怎么处理的

**Comment by Aurora11111** [comment]
@dlml 80%的数据是自己模仿真实数据造出来的,小部分用真实场景数据

**Comment by wait1988** [comment]
请问数据长短不一的时候，图片补长之后，空白部分需要标注吗 @wenlihaoyu
