### ISSUE TITLE
关于速度，80%的时间花在rotate_cut_img()，是正常的吗？如何优化？

### ISSUE THREAD

**Issue by mocorr** [chineseocr/chineseocr#494]
先说我的环境：Linux，单GPU，框架全部用keras（用其他框架应该也差不多）。
记录了一下各部分的耗时，在有gpu的情况下，其实深度学习任务并不怎么花时间；
相反，80%的时间是花在crnn前的rotate_cut_img（在原图中旋转并裁剪出单行文字用于crnn的这个函数）。

以一张A4书页为例，共耗时2.9s，其中rotate_cut_img共耗时2.38s，crnn实际一共只花了0.14s。

请问这一部分作者有考虑过优化吗？
除了在这里加个多线程有无其他方式提速呢？

**Comment by wenlihaoyu** [comment]
用这个函数修改即可https://github.com/chineseocr/darknet-ocr/blob/master/dnn/main.py#L39
即先安box的外接矩形进行crop操作，然后再小图上旋转，这样速度就很快。

**Comment by mocorr** [comment]
> 用这个函数修改即可https://github.com/chineseocr/darknet-ocr/blob/master/dnn/main.py#L39
> 即先安box的外接矩形进行crop操作，然后再小图上旋转，这样速度就很快。

超级感谢 我真的太废柴了，我只想得到直接按外接矩形裁剪，结果效果就不理想
