### ISSUE TITLE
请问会公开yolo3的训练code么，yolo3除了在时效上好于ctpn, 准确度上有改进吗

### ISSUE THREAD

**Issue by xikunlun001** [chineseocr/chineseocr#5]
请问会公开yolo3的训练code么，
yolo3除了在时效上优于ctpn, 准确度上有改进吗

**Comment by wenlihaoyu** [comment]
后面有时间了会公开的。我主要将这一块用于发票票据的识别，yolo3对比ctpn，CPU环境大概是2-3秒（ctpn可能要接近10秒），GPU小于1秒。对整体而言，在票据识别，yolo3对比ctpn（ocr用同一引擎），准确率会高10%左右。

**Comment by xikunlun001** [comment]
@wenlihaoyu 
我测了下同样的图片集，用您之前写的ctpn + crnn 在cpu上是是15秒一张图
用了现在您公布的yolo3 + crnn 变成 20秒一张了

我自己在后端print 出来 和 您提供的8080前端我都试了反而比之前的慢，能不能请问下是不是我哪儿弄错了还是怎么

**Comment by Aurora11111** [comment]
@wenlihaoyu
遇到和xikunlun001 一样的问题，试了下不管图片大小都是20多s一张

**Comment by xikunlun001** [comment]
我看了下 好像是 detect_np里面的dn.predict_image(net, im)这步耗时过多
这个应该是调了darknet里C写的.so
不知道目前是否有解决方法还是暂时就是这个时间
@wenlihaoyu

**Comment by xikunlun001** [comment]
@wenlihaoyu 
我看了下  应该是 dn.predict_image(net, im) 耗时的
这一步应该是掉了yolo3中的C的Python接口
不知道您那边的时间是否也是比ctpn慢

**Comment by blackarrow3542** [comment]
When I try 
`./darknet detector test ../chineseocr/models/text.data ../chineseocr/models/text.cfg ../chineseocr/models/text.weights image.jpeg`
I got  Predicted in 0.036178 seconds.
However app.py is very slow...

**Comment by xikunlun001** [comment]
@blackarrow3542 
Could you provide details of the way you tried?
I'm a bit confused of './darknet detector test' .
I can't find detector and test files in 'darknet' directory. 

Many thanks,

**Comment by blackarrow3542** [comment]
@xikunlun001 
我按照这个tutorial来的
https://pjreddie.com/darknet/yolo/
在下载的darknet directory里面运行，运行时把命令里的模型地址换成这个chineseocr的，再随便找了一张发票的图片。
我觉得我compile没问题，我还在找问题出在哪。。。对了 .cfg 那个file可以改成test 把train的两行comment掉

**Comment by xikunlun001** [comment]
@blackarrow3542 好的，我去试试  有update的话我会更新上来
Many thanks~

**Comment by xikunlun001** [comment]
@blackarrow3542
我测了下CPU的时间没变化还是17秒左右...
不过你最后说的那个text.cfg我没改, 没弄明白哪一部分是Training的

**Comment by xikunlun001** [comment]
@wenlihaoyu 
我用gpu测了下 detection用时0.1X秒
第一张会慢一点到1秒可能是因为要loading一些东西，后面都是0.1秒
我直接去darknet 测同样的图用你的方法是0.03秒

**Comment by wenlihaoyu** [comment]
原生版darkne的CPU版本还不支持多线程，也没有对CPU计算加速，所以很慢，后面会公布多CPU优化的darknet版本。或者可以用NNPACK或者openblas去加速。最简单的方式，直接转换为keras模型（cpu也是1-2秒），不需要做什么优化，也方便版本升级。转换方式详细参考https://github.com/qqwweee/keras-yolo3.git。

**Comment by xikunlun001** [comment]
@wenlihaoyu 感谢~

**Comment by piaobuliao** [comment]
@wenlihaoyu 
“ 。对整体而言，在票据识别，yolo3对比ctpn（ocr用同一引擎），准确率会高10%左右。”
你值得是文字检测的准确率？
想问下用ctpn检测和YOLO3用同样的数据训练然后去检测吗？

**Comment by xikunlun001** [comment]
@wenlihaoyu 
我转成keras版本之后检测的效果不好，不知道是不是yolo_anchor的问题，我用的是您提供的链接自带的yolo_anchor. 请问能提供下这个model 适用的yolo_anchor么

**Comment by xikunlun001** [comment]
@wenlihaoyu 
我试着转成了keras版本的model, 但是用keras跑出来的和darknet原生(没用您的adjust)的跑出来结果似乎不同。不知道是不是因为darknet穿进去的时候Image的type 是 darknet.image已经经过darknet的处理带参的 或者其他方面的问题。不知道您那边是否试过转keras的测试呢，除了model外还有哪些部分需要修改。

感谢~

**Comment by wenlihaoyu** [comment]
@xikunlun001 转换后，要动态输入神经网络图像的大小，不能是416*416。

**Comment by xikunlun001** [comment]
@wenlihaoyu 感谢，请问是只需要传实际的imageW, imageH就可以了吗？因为我看code好像您有一个function是 array_to_image， 这一部好像传了好几个参数进去。
如果方便的话是否方便分享下keras的读取部分的代码
tracychen332@gmail.com

感谢

**Comment by moondaiy** [comment]
@xikunlun001 我也正在尝试用keras转换后的model 进行预测, 请问下预测的代码使用作者提供的那个git中的yolo_video.py可以么? 里面可以直接进行image预测.但是效果很差..我不知道应该用那份代码对keras模型进行预测

**Comment by blackarrow3542** [comment]
I will answer my own question...
With ctpn and keras vgg crnn model. It takes me 3s for an image, with about 50 text boxes.  I use batch prediction with the crnn model in keras to make it faster. ctpn takes 1.5s, crnn takes the other 1.5s 
With the yolo3 and pytorch, the yolo3 is really fast, which takes less than 1s. But the pytorch prediction takes more than 10s when there are many text boxes(each takes less than 1s).  I guess we can improve the performance of the pytorch crnn model with batch prediction.

P.S I'm using 1700x and gtx 1080ti.

**Comment by xikunlun001** [comment]
@moondaiy 可以用yolo_video.py预测image  但是效果完全不对  不知道是哪个参数不对

**Comment by xikunlun001** [comment]
@blackarrow3542 我用GPU的话 一张图只需要0.1S 大概15个box
你是不是就测了一张图，会不会把load model的时间也算进去了

**Comment by blackarrow3542** [comment]
@xikunlun001 这么快，就算用上GPU，我光yolo3这部分就要0.1S了。后面pytorch crnn部分每个box要大概0.05~0.2秒。然后70多个box时间就上去了。用keras的话我可以把所有box按一个batch处理 就快了。

**Comment by xikunlun001** [comment]
@wenlihaoyu yolo3这部分是0.1s
crnn那部分需要把GPU改成True, 要不CRNN那部分走的是CPU。
我大概15个boxes, CRNN部分用GPU也是0.1s左右
crnn部分用CPU大概是你说的那个时间，你把crnn部分改成GPU就快很多了

**Comment by blackarrow3542** [comment]
@xikunlun001 谢谢，一开始没看到GPU=False。
