### ISSUE TITLE
error bunzip2: not found

### ISSUE THREAD

**Issue by for1314ai** [chineseocr/chineseocr#553]
[/root/anaconda3] >>> PREFIX=/root/anaconda3
Anaconda3-2019.03-Linux-x86_64.sh: 353: bunzip2: not found
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

**Comment by for1314ai** [comment]
update dockerfile line six to :`RUN apt-get install  libsm6 libxrender1 libxext-dev gcc bzip2 -y`

**Comment by weiwei335302680** [comment]
> [/root/anaconda3] >>> PREFIX=/root/anaconda3 Anaconda3-2019.03-Linux-x86_64.sh: 353: bunzip2: not found tar: This does not look like a tar archive tar: Exiting with failure status due to previous errors
