### ISSUE TITLE
Yolo-v3 改进

### ISSUE THREAD

**Issue by sdy1106** [chineseocr/chineseocr#58]
![image](https://user-images.githubusercontent.com/22407365/46244176-a6642500-c40d-11e8-86c7-985c43208cfe.png)

作者你好，我想问一下，这种分隔比较开的字，现在的yolov3还不能识别到一行（比如：品牌，款号等等），请问有什么建议的优化方法嘛？

**Comment by wenlihaoyu** [comment]
调整model函数中alph参数即可，默认是0.1，你可以设置大一点
