### ISSUE TITLE
请问一下ipython app.py之后只输出了http://0.0.0.0:8080/怎么办

### ISSUE THREAD

**Issue by mocorr** [chineseocr/chineseocr#88]

**Comment by mocorr** [comment]
linux系统，没有图形化界面，对web方面不了解，希望能运行的各位路过解答下。正常运行是什么样的，弹出一个网页？

**Comment by NormalAppler** [comment]
在window浏览器中访问http://linuxip:8080/ocr就能看到页面了

**Comment by mocorr** [comment]
@NormalAppler 原来是这样，谢谢你~ 我昨天就直接把web部分删掉了，可以运行。

**Comment by ljg-lixufeng** [comment]
我的在win上出现页面了，可是选择照片点了不管用
