### ISSUE TITLE
yolov3 text detection训练思路

### ISSUE THREAD

**Issue by Aurora11111** [chineseocr/chineseocr#90]

**Comment by wenlihaoyu** [comment]
单个字符标注为一个box，训练即可。或者可以按行标注，然后根据字符数（或者简单的分割算法）去转换一下也可以

**Comment by Aurora11111** [comment]
@wenlihaoyu 
![predictions](https://user-images.githubusercontent.com/39044868/48177402-5141fa00-e34f-11e8-8358-f632ab48cb73.png)
你看你的yolov3检测出来水平是固定宽度的,为什么你的text.cfg里的anchor不像是直接用小box数据集聚类得到的呢

**Comment by rkshuai** [comment]
你知道是什么愿意了吗？

**Comment by rkshuai** [comment]
你知道是什么原因了吗？

**Comment by rkshuai** [comment]
能不能留一下你的联系方式，我们讨论一下呢？
