### ISSUE TITLE
error: (-212:Parsing error) Failed to parse NetParameter file

### ISSUE THREAD

**Issue by zenwan** [chineseocr/chineseocr#92]
error: OpenCV(3.4.2) /io/opencv/modules/dnn/src/darknet/darknet_io.cpp:784: error: (-212:Parsing error) Failed to parse NetParameter file: /home/fltdp/workspaces/chineseocr/models/models/text.cfg in function 'ReadNetParamsFromCfgFileOrDie'

**Comment by wangpupanjing** [comment]
我也遇到这个问题了

**Comment by tommy9301122** [comment]
在執行 test.ipynb 時也有遇到相同問題~
解決方法：
將 models 資料夾內的 text.cfg 刪掉重載一次
應該是因為模型權重檔案壞掉了
