### ISSUE TITLE
请问opencv的dnn模块怎么用GPU加速呢？

### ISSUE THREAD

**Issue by mocorr** [chineseocr/chineseocr#93]
我在windows上部署的，所以没有用darknet，直接选择了opencv的dnn模块。
其他部分都很正常，ocr部分，crnn在GPU下只用了不到0.5秒。
但是opecv的dnn模块做yolo检测，用了两秒半，我想是没有使用GPU。
但我在网上搜索了很久也没有弄懂要怎么才能让opencv的dnn支持CUDA。
希望能指导一下，非常感谢。

**Comment by mocorr** [comment]
我又查了一些资料，似乎opencv的dnn只支持intel自家的GPU？英伟达的好像不可以？
但是为什么别人普遍都说用cpu也很快呢？都是0.2s左右
可我的cpu要两三秒。

**Comment by wenlihaoyu** [comment]
目前opencv dnn还不支持cuda，可以参考如果是intel 处理器，可以尝试安装 OpenVINO Toolkit。
opencv dnn 调用yolo要不了2秒，一般就1秒内就能完成，检查你环境配置是否有问题，或者debug看一下是dnn哪一部分耗时

**Comment by mocorr** [comment]
自己来终结一下这个问题。
opencv dnn不支持cuda.
windows也不要折腾darknet(专门装了cgwin来编译，在cpu上跑起来了，但是gpu的路径emmm)，老老实实转成keras，tensorflow后端调用GPU还是挺快的。
如果能装linux还是linux最好，发现在linux上跑，同样是keras预测，速度又快了一些。

**Comment by xchsh** [comment]
> 我在windows上部署的，所以没有用darknet，直接选择了opencv的dnn模块。
> 其他部分都很正常，ocr部分，crnn在GPU下只用了不到0.5秒。
> 但是opecv的dnn模块做yolo检测，用了两秒半，我想是没有使用GPU。
> 但我在网上搜索了很久也没有弄懂要怎么才能让opencv的dnn支持CUDA。
> 希望能指导一下，非常感谢。

请问楼主的DNN模块GPU加速是怎么设置的，我直接使用 
        MobileNet.setPreferableBackend(DNN_BACKEND_DEFAULT);
	MobileNet.setPreferableTarget(DNN_TARGET_OPENCL);
进行GPU设置，处理速度反而下降了
运行环境：Hi3751V811，opencv3.4.1

**Comment by luyuhua** [comment]
我config中配置的opencv。在文字方向预测和detect两个模型中做预测。也就是用到cv2.dnn.去预测的模型。但是我这显示用到了GPU资源，而且速度比我用tensorflow cpu版本快很多。难道opencv支持cuda了？还是他内部某些函数优化到gpu上了？求解释。
opencv 版本是3.4.2。
预测代码如下：
`from config import yoloCfg,yoloWeights,opencvFlag
from config import AngleModelPb,AngleModelPbtxt
from config import IMGSIZE
import cv2
import numpy as np
textNet  = cv2.dnn.readNetFromDarknet(yoloCfg,yoloWeights)

def text_detect(img):
    thresh=0
    h,w = img.shape[:2]
    inputBlob = cv2.dnn.blobFromImage(img, scalefactor=0.00390625, size=IMGSIZE,swapRB=True ,crop=False);
    textNet.setInput(inputBlob)
    pred = textNet.forward()
    cx = pred[:,0]*w
    cy = pred[:,1]*h
    xmin = cx - pred[:,2]*w/2
    xmax = cx + pred[:,2]*w/2
    ymin = cy - pred[:,3]*h/2
    ymax = cy + pred[:,3]*h/2
    scores = pred[:,4]
    indx = np.where(scores>thresh)[0]
    scores = scores[indx]
    boxes = np.array(list(zip(xmin[indx],ymin[indx],xmax[indx],ymax[indx])))
    return boxes,scores

from PIL import Image
p = './test/2.jpg'
img = Image.open(p).convert("RGB")

boxes,scores = text_detect(np.array(img))
print(boxes,scores)`

GPU运行情况如下：
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.66                 Driver Version: 384.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P4            On   | 00000000:00:07.0 Off |                    0 |
| N/A   33C    P0    23W /  75W |    119MiB /  7606MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     21887    C   ...uhua/anaconda3/envs/chineseocr/bin/python   109MiB |
+-----------------------------------------------------------------------------+

**Comment by ccl-private** [comment]
https://www.pyimagesearch.com/2020/02/03/how-to-use-opencvs-dnn-module-with-nvidia-gpus-cuda-and-cudnn/

**Comment by u19900101** [comment]
> https://www.pyimagesearch.com/2020/02/03/how-to-use-opencvs-dnn-module-with-nvidia-gpus-cuda-and-cudnn/

这个是不是不支持windows下的加速？

**Comment by ccl-private** [comment]
@u19900101 支持的，弄好cuda，源码编译最新opencv(开启dnn cuda)，然后你要根据报错自己解决一些依赖问题。还是建议你使用linux系统。

**Comment by u19900101** [comment]
cuda已经弄好了，源码好编译吗？另外求问一下大佬，你在做手势识别吗，如果方便的话可否加下你微信

**Comment by ccl-private** [comment]
@u19900101 依赖环境弄齐了，直接等他编译好就完事了。不过opencv这个cuda的加速不够好，我之前测试没有tensorflow之类的框架来得快。
手势识别推荐openpose的那个。

**Comment by u19900101** [comment]
我现在也在看这个，但还是太慢了，达不到实时要求，我的显卡1060


 
---原始邮件---
发件人: "ccl"<notifications@github.com&gt;
发送时间: 2020年5月29日(星期五) 中午11:29
收件人: "chineseocr/chineseocr"<chineseocr@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"u19900101"<815000342@qq.com&gt;;
主题: Re: [chineseocr/chineseocr] 请问opencv的dnn模块怎么用GPU加速呢？ (#93)




 
@u19900101 依赖环境弄齐了，直接等他编译好就完事了。不过opencv这个cuda的加速不够好，我之前测试没有tensorflow之类的框架来得快。
 手势识别推荐openpose的那个。
